// packages/vite/examples/vue/src/components/Panel/Panel.vue
<script setup lang="ts">
  import { shallowReactive } from 'vue';
  import classes from './Panel.module.css';

  const state = shallowReactive({ isOpen: false });
</script>

<template>
  <div :class="classes.Panel">
    <div :class="[classes['panel' + '-' + 'header'], { isOpen: state.isOpen }]">
      <div :class="classes['panel-box']">
        this is the Panel Header
      </div>
    </div>
    this is the content
    <div :class="[classes['panel-footer'], { isOpen }]">
      <div :class="classes['panel-box']">
        this is the panel footer
      </div>
    </div>
  </div>
</template>

// packages/vite/examples/react/src/components/Panel/Panel.tsx
import { useState } from 'react';
import clsx from 'clsx';
import classes from './Panel.module.css';

export default function Panel() {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <div className={classes.Panel}>
            <div className={clsx(classes['panel' + '-' + 'header'], { isOpen })}>
                <div className={classes['panel-box']}>
                    this is the Panel Header
                </div>
            </div>
            this is the content
            <div className={clsx(classes['panel-footer'], { isOpen })}>
                <div className={classes['panel-box']}>
                    this is the panel footer
                </div>
            </div>
        </div>
    );
}
